name: tidytime
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3+1
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  intl: ^0.19.0
  numberpicker: ^2.1.2
  flutter_slidable: ^3.1.1
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  provider: ^6.1.2
  flutter_xlider: ^3.5.0
  drag_and_drop_lists: ^0.4.1
  permission_handler: ^10.4.3
  fuzzywuzzy: ^1.2.0
  http: ^1.2.2
  html_unescape: ^2.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/warning-sign.png
    - assets/images/checked.png

    - assets/images/rooms/attic.png
    - assets/images/rooms/basement.png
    - assets/images/rooms/bathroom.png
    - assets/images/rooms/bedroom.png
    - assets/images/rooms/childrens-bedroom.png
    - assets/images/rooms/Closet.png
    - assets/images/rooms/corridor.png
    - assets/images/rooms/dining-room.png
    - assets/images/rooms/entryway.png
    - assets/images/rooms/entire-home.png
    - assets/images/rooms/garage.png
    - assets/images/rooms/guest-bedroom.png
    - assets/images/rooms/home-gym.png
    - assets/images/rooms/home-office.png
    - assets/images/rooms/kitchen.png
    - assets/images/rooms/laundry-room.png
    - assets/images/rooms/living-room.png
    - assets/images/rooms/master-bedroom.png
    - assets/images/rooms/nursery.png
    - assets/images/rooms/pantry.png
    - assets/images/rooms/play-room.png
    - assets/images/rooms/storage-room.png
    - assets/images/rooms/terrace-patio.png
    - assets/images/rooms/default.png

    - assets/images/profile/default_avatar.png
    - assets/images/profile/M1.png
    - assets/images/profile/M2.png
    - assets/images/profile/M3.png
    - assets/images/profile/W1.png
    - assets/images/profile/W2.png
    - assets/images/profile/W3.png

